// Generated by gencpp from file sensor_msgs/LaserPoints.msg
// DO NOT EDIT!


#ifndef SENSOR_MSGS_MESSAGE_LASERPOINTS_H
#define SENSOR_MSGS_MESSAGE_LASERPOINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/common/serialization.h>
#include <ros/common/message-operations.h>

#include <ros/sensor_msgs/header.h>

namespace sensor_msgs
{
template <class ContainerAllocator>
struct LaserPoints_
{
  typedef LaserPoints_<ContainerAllocator> Type;

  LaserPoints_()
    : header()
    , points_x()
    , points_y()
    , intensities()  {
    }
  LaserPoints_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , points_x(_alloc)
    , points_y(_alloc)
    , intensities(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _points_x_type;
  _points_x_type points_x;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _points_y_type;
  _points_y_type points_y;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _intensities_type;
  _intensities_type intensities;





  typedef boost::shared_ptr< ::sensor_msgs::LaserPoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_msgs::LaserPoints_<ContainerAllocator> const> ConstPtr;

}; // struct LaserPoints_

typedef ::sensor_msgs::LaserPoints_<std::allocator<void> > LaserPoints;

typedef boost::shared_ptr< ::sensor_msgs::LaserPoints > LaserPointsPtr;
typedef boost::shared_ptr< ::sensor_msgs::LaserPoints const> LaserPointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_msgs::LaserPoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_msgs::LaserPoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sensor_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/home/sineva/temp/temp_ws/src/sensor_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sensor_msgs::LaserPoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_msgs::LaserPoints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_msgs::LaserPoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_msgs::LaserPoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_msgs::LaserPoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_msgs::LaserPoints_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_msgs::LaserPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ea7dcec691d3b8b692bccbe764acc3e";
  }

  static const char* value(const ::sensor_msgs::LaserPoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ea7dcec691d3b8bULL;
  static const uint64_t static_value2 = 0x692bccbe764acc3eULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_msgs::LaserPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/LaserPoints";
  }

  static const char* value(const ::sensor_msgs::LaserPoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_msgs::LaserPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
float32[] points_x\n\
float32[] points_y\n\
float32[] intensities\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::sensor_msgs::LaserPoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_msgs::LaserPoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.points_x);
      stream.next(m.points_y);
      stream.next(m.intensities);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LaserPoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_msgs::LaserPoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_msgs::LaserPoints_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "points_x[]" << std::endl;
    for (size_t i = 0; i < v.points_x.size(); ++i)
    {
      s << indent << "  points_x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.points_x[i]);
    }
    s << indent << "points_y[]" << std::endl;
    for (size_t i = 0; i < v.points_y.size(); ++i)
    {
      s << indent << "  points_y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.points_y[i]);
    }
    s << indent << "intensities[]" << std::endl;
    for (size_t i = 0; i < v.intensities.size(); ++i)
    {
      s << indent << "  intensities[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.intensities[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_MSGS_MESSAGE_LASERPOINTS_H
